---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name                   : Create DB instance with added AWS KMS Encryption Enabled
    rds_instance           :
      id                   : "{{ db_identifier }}"
      state                : "{{ db_state }}"
      region               : "{{ db_region }}"
      engine               : "{{ db_engine }}"
      username             : "{{ db_username }}"
      password             : "{{ db_password }}"
      db_instance_class    : "{{ db_instance_class }}"
      allocated_storage    : "{{ db_allocated_storage }}"
      storage_encrypted    : true
      skip_final_snapshot  : true
